# Generated by Django 5.0.1 on 2024-02-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
